export PATH="$PATH:"
alias del="source ~/vimfiles/bash/move_to_trash.sh"
#alias time_out="python ~/my_wiki/script/python/time_out.py"
alias time_out="python ~/my_wiki/script/python/time_out/time_out.py"
alias libreoffice="/C/Program\ Files/LibreOffice\ 5/program/soffice.exe"
alias gvim="/C/Program\ Files\ \(x86\)/Vim/vim80/gvim.exe"
alias eclimd="/e/tools/eclipse-javascript-neon-R-win32/eclipse/eclimd.bat"
alias maxthon="/C/Program\ Files\ \(x86\)/Maxthon5/Bin/MxStart.exe"
alias zhaoshang="/C/Windows/SysWOW64/PersonalBankPortal.exe"
alias shouyinji="/D/lhy/tools/green_software/CRadio/CRadio.exe"
alias 263="/C/Program\ Files\ \(x86\)/263\ Enterprise\ Messenger/263em.exe"

export black_bean="/D/lhy/project/black_bean"
